### ISSUE TITLE
Piping error?

### ISSUE THREAD

**Issue by avoidwork** [avoidwork/turtle.io#354]
```console
Routed request to disk
_stream_readable.js:481
  dest.on('unpipe', onunpipe);
      ^

TypeError: Cannot read property 'on' of undefined
    at ReadStream.Readable.pipe (_stream_readable.js:481:7)
    at TurtleIO.send (/Users/jason/Projects/turtle.io/lib/turtleio.js:640:12)
    at TurtleIO.handle (/Users/jason/Projects/turtle.io/lib/turtleio.js:322:13)
    at /Users/jason/Projects/turtle.io/lib/turtleio.js:563:17
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by avoidwork** [comment]
I was running an outdated clone :+1:
