### ISSUE TITLE
Error with test code

### ISSUE THREAD

**Issue by dnichk** [avoidwork/turtle.io#358]
I was just running through the example code on my desktop, and ran into the following:

```
sudo node server.js 
/Users/dustin/node_modules/turtle.io/index.js:12
function factory (cfg = {}, errHandler = null) {
                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/dustin/Desktop/www/server.js:1:78)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

My server.js contains (I'm using a hosts file):

```
var TurtleIO = require("turtle.io"),
    server = new TurtleIO();

server.start({
	default : "bf.lan",
	uid     : 100,
	port    : 80,
	root    : "/Users/dustin/Desktop/www",
	vhosts  : {
		"bf.lan"      : "bf.lan",
		"www.bf.lan"  : "bf.lan"
	}
});
```

NPM version:

```
npm -v
3.8.3
```

Node version:

```
node -v
v5.10.1
```

OS X:

```
sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34
```

Thoughts?

**Comment by avoidwork** [comment]
Needs 6.0

**Comment by avoidwork** [comment]
To explain a little further, <7.0 worked with 0.12+, with 7.0 I removed babel 'cause nodejs 6.0 happened.
